include:
  - package:flutter_lints/flutter.yaml
  - package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore # for freezed/json
    todo: error # TODOs are now errors
    avoid_dynamic_calls: error # JSON false positives can be suppressed per-file
    discarded_futures: error
    body_might_complete_normally_nullable: error
    public_member_api_docs: warning # enforce documentation
    always_specify_types: ignore
    avoid_print: error # Don't allow print statements in production code

  exclude:
    - lib/gen/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.mocks.dart
    - test/**.mocks.dart

linter:
  rules:
    # ---- Core Strictness ----
    - always_declare_return_types
    - prefer_final_locals
    - prefer_final_in_for_each
    - prefer_final_fields
    - avoid_unused_constructor_parameters
    - unnecessary_statements
    - unnecessary_getters_setters
    - avoid_renaming_method_parameters
    - avoid_redundant_argument_values
    - avoid_returning_null_for_void
    - avoid_catching_errors
    - avoid_equals_and_hash_code_on_mutable_classes
    - test_types_in_equals
    - exhaustive_cases
    - always_put_required_named_parameters_first
    - always_use_package_imports: ignore
    - one_member_abstracts: ignore
    # Note: always_specify_types removed - conflicts with omit_local_variable_types from very_good_analysis
    # very_good_analysis provides better type inference rules
    - avoid_annotating_with_dynamic
    - type_annotate_public_apis
    - prefer_typing_uninitialized_variables

    # ---- Clean Imports & Structure ----
    - directives_ordering
    - sort_child_properties_last
    - sort_constructors_first
    - implementation_imports
    # Note: prefer_relative_imports removed - conflicts with always_use_package_imports from very_good_analysis
    # very_good_analysis prefers package imports (better for maintainability)

    # ---- Flutter UI Strictness ----
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - sized_box_shrink_expand
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_key_in_widget_constructors
    - avoid_unnecessary_containers
    - use_build_context_synchronously

    # ---- Code Style & Readability ----
    - prefer_single_quotes
    - prefer_expression_function_bodies
    - always_put_control_body_on_new_line
    - prefer_if_null_operators
    - unnecessary_lambdas
    - unnecessary_await_in_return
    - avoid_empty_else
    - cascade_invocations
    - avoid_void_async
    - avoid_function_literals_in_foreach_calls
    - prefer_foreach
    - prefer_for_elements_to_map_fromIterable
    - prefer_const_declarations
    - avoid_multiple_declarations_per_line
    - prefer_interpolation_to_compose_strings

    # ---- Error-Prone Pattern Prevention ----
    - cancel_subscriptions
    - close_sinks
    - no_logic_in_create_state
    - only_throw_errors
    - use_string_buffers
    - avoid_slow_async_io
    - avoid_null_checks_in_equality_operators
    - avoid_field_initializers_in_const_classes
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator

    # ---- Maintainable Collections ----
    - prefer_spread_collections
    - prefer_collection_literals
    - unnecessary_to_list_in_spreads
    - avoid_single_cascade_in_expression_statements

    # ---- Condition Simplification ----
    - avoid_bool_literals_in_conditional_expressions
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
